export const ADD_POST = "ADD_POST"
export const UPDATE_POST_TEXT = "UPDATE_POST_TEXT"
export const DELETE_POST = "DELETE_POST"

export const ADD_MESSAGE = "ADD_MESSAGE"
export const UPDATE_MESSAGE_TEXT = "UPDATE_MESSAGE_TEXT"

export const CHANGE_FRIEND_STATUS = "CHANGE_FRIEND_STATUS"
export const ADD_FRIEND = "ADD_FRIEND"
export const SET_FRIENDS = "SET_FRIENDS"

export const LEAVE_GROUP = "LEAVE_GROUP"